apiVersion: apps/v1
kind: Deployment
metadata:
    name: argo-cd-argocd-server
    namespace: argocd
spec:
    template:
        spec:
            containers:
                - name: argocd-server
                  envFrom:
                      - secretRef:
                            name: argocd-ts-values
