apiVersion: v1
kind: ServiceAccount
metadata:
    name: secrets-store-csi-driver
    namespace: kube-system
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::905418091519:role/eks-secrets-csi-role-argocd-cluster
