apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: tailscale-secrets
    namespace: tailscale
spec:
    provider: aws
    parameters:
        objects: |
            - objectName: "TS_CLIENT_ID"
              objectType: "secretsmanager"
              objectVersion: "AWSCURRENT"
            - objectName: "TS_CLIENT_SECRET"
              objectType: "secretsmanager"
              objectVersion: "AWSCURRENT"
    secretObjects:
        - secretName: "argocd-ts-values"
          type: Opaque
          data:
              - objectName: "TS_CLIENT_ID"
                key: "TS_CLIENT_ID"
              - objectName: "TS_CLIENT_SECRET"
                key: "TS_CLIENT_SECRET"
