apiVersion: v1
kind: Service
metadata:
    name: argocd-server
    namespace: argocd
    annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "argocd"
        argocd.argoproj.io/sync-wave: "20"
spec:
    type: ClusterIP
    selector:
        app.kubernetes.io/name: argocd-server
    ports:
        - name: https
          port: 443
          targetPort: 8080
