apiVersion: v1
kind: Secret
metadata:
    name: sandbox-staging-secret
    labels:
        argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
    name: "sandbox-staging"
    server: "https://F1B549F6173F7F66ADE68547D4869592.sk1.us-west-1.eks.amazonaws.com"
    config: |
        {
          "awsAuthConfig": {
            "clusterName": "staging-cluster",
            "roleARN": "arn:aws:iam::905418091519:role/argocd-eks-manager-argocd-cluster"
          },
          "tlsClientConfig": {
            "insecure": false,
            "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWFZaWTArZlZmRW93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1UTXhNalV6TkRGYUZ3MHpOVEV4TVRFeE1qVTROREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMzdThpL3Vud3ZWV21xVVM0emxhRHpGNHA1WWx2NytvVHROeXE3cWdWbWRaRm9GQlgwVXRNVWh6enoKdnNVWlNvVnF6ajFSUENyZ29lOU1LMFUwcmxscG43Y0RtQ0Z5VnNtOFEzR0xpbDRjQmNiVDFuanlaTmVlc0JKUwpESStUOGhWcnllSS8yczg3V1JYM3BVcjR2cHgxd2JHQWhobGdWYmZwc1p0blNCT256SmRqV3hjbEQxcTN2dk4wCmp0czlsNG1PTEFHL3NtTjJHTjc2NWN0WVFFNEZYdE4waktZTHZ4TEVxZXRrdnIwb3YxS2k2eFN3WnBtTUZUT1kKZFFWM2RBYUZ1RktPdlR5K3ZpbVRVODJ4TURRaWQwVWw1b2ZCcWhLZC91bDdOUnNCMGxIMWFySDhGczhMejFWVQovcmV3TE9zRFU0Y0pOUU0zYUMvQ0dBSVRBUU1WQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRd0lWT29lNVdxMVpHekZJLzRGMnlUNGx2R296QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVZwclpnY2EvMQpNNUhGSE9uMWVselo2c1pvQVJwanBiNXFWN1NtZHUvdTkzdHgxeDFES2FlY0JEdzZZR2ppV21hVjEzSFFqQWhICmgxWGkvSzEzTVZ0cEkyRGE3cDdNazJVaEZ2M1VpWWdiYU44bE90ZE90SFk5ajZVdHJROEc0U3h4L2lwQ1pqM2kKeHVlQW1qNitXQU1uZzdoSkkwb1JSOENGbHRndDliNEF1R010U3BLMlB4Z2ZpOENVYStIVWlhdTlReXJ4WkxuYwp6Vm9TL0VjZUg2NUVHSC9ETldGenE3SjFmSExFR3k0OVR2UWhOMUF3a3I2clRldGNtZWJ2OU1oWTdOQzl5Sk1rCmcxczNETE9lNjlZS0pNQ3pjV2x3YVB6dGUxL3BKbklONGxFU2M5YkZwVzdXM3VNL01lM3BRNEg1ZHZQZHhqL3AKSkpZdkl0VGtLZEVPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          }
        }
