apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: external-secrets
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: "0"
spec:
    project: default
    source:
        repoURL: "https://github.com/abhizer/argocd-test.git"
        targetRevision: HEAD
        path: manifests/external-secrets
    destination:
        server: https://kubernetes.default.svc
        namespace: external-secrets
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
    dependencies:
        - app-of-apps
