# Example addition to apps/app-of-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: external-secrets
    namespace: argocd
spec:
    project: default
    source:
        repoURL: "https://github.com/abhizer/argocd-test.git" # Your repo URL
        targetRevision: HEAD
        path: manifests/external-secrets
    destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
