apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: sandbox-staging
    namespace: argocd
spec:
    project: default
    source:
        repoURL: "https://github.com/abhizer/argocd-test.git"
        targetRevision: HEAD
        path: manifests/sandbox-staging
    destination:
        name: sandbox-staging
        namespace: feldera
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
