apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: aws-secrets-provider
    namespace: argocd
spec:
    project: default
    sources:
        - repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
          chart: secrets-provider-aws
          targetRevision: "1.5.4"
    destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
