apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: tailscale-operator
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: "10"
spec:
    project: default
    source:
        repoURL: "https://github.com/abhizer/argocd-test.git"
        targetRevision: HEAD
        path: manifests/tailscale
    destination:
        server: https://kubernetes.default.svc
        namespace: tailscale
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
