# apps/tailscale.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: tailscale-operator
    namespace: argocd
spec:
    project: default
    sources:
        - path: manifests/tailscale-operator
          repoURL: "https://github.com/abhizer/argocd-test.git"
          targetRevision: main
        - repoURL: "https://pkgs.tailscale.com/helmcharts"
          targetRevision: "1.90.5"
          helm:
              values: |
                  oauth:
                    clientId: TS_CLIENT_ID
                    clientSecret: TS_CLIENT_SECRET
                  replicaCount: 1
    destination:
        server: https://kubernetes.default.svc
        namespace: tailscale
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
